[build]
  publish = "dist/f1nal-lap"  # Asegúrate de que esta es la ruta correcta a tu carpeta de salida
  command = "ng build --configuration production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
